/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as OrderTokenRouteImport } from './routes/order.$token'
import { Route as SuperAdminAuthedRouteImport } from './routes/super-admin/_authed'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as AdminAuthedAccountRouteImport } from './routes/admin/_authed/account'
import { Route as AdminAuthedAnalyticsRouteImport } from './routes/admin/_authed/analytics'
import { Route as AdminAuthedDeliveryRouteImport } from './routes/admin/_authed/delivery'
import { Route as AdminAuthedHoursRouteImport } from './routes/admin/_authed/hours'
import { Route as AdminAuthedMenuRouteImport } from './routes/admin/_authed/menu'
import { Route as AdminAuthedPromotionsRouteImport } from './routes/admin/_authed/promotions'
import { Route as AdminAuthedStaffRouteImport } from './routes/admin/_authed/staff'
import { Route as AdminResetPasswordTokenRouteImport } from './routes/admin/reset-password.$token'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'
import { Route as SuperAdminAuthedIndexRouteImport } from './routes/super-admin/_authed/index'
import { Route as SuperAdminAuthedActivityRouteImport } from './routes/super-admin/_authed/activity'
import { Route as SuperAdminAuthedAdminsRouteImport } from './routes/super-admin/_authed/admins'
import { Route as SuperAdminAuthedRestaurantsRouteImport } from './routes/super-admin/_authed/restaurants'
import { Route as SuperAdminAuthedSettingsRouteImport } from './routes/super-admin/_authed/settings'
import { Route as AdminAuthedOrdersIndexRouteImport } from './routes/admin/_authed/orders.index'
import { Route as AdminAuthedOrdersIdRouteImport } from './routes/admin/_authed/orders.$id'
import { Route as SuperAdminAuthedRestaurantsIdRouteImport } from './routes/super-admin/_authed/restaurants.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTokenRoute = OrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAuthedRoute = SuperAdminAuthedRouteImport.update({
  id: '/super-admin/_authed',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedAccountRoute = AdminAuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedAnalyticsRoute = AdminAuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDeliveryRoute = AdminAuthedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedHoursRoute = AdminAuthedHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedMenuRoute = AdminAuthedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedPromotionsRoute = AdminAuthedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedStaffRoute = AdminAuthedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminResetPasswordTokenRoute = AdminResetPasswordTokenRouteImport.update({
  id: '/admin/reset-password/$token',
  path: '/admin/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAuthedIndexRoute = SuperAdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminAuthedRoute,
} as any)
const SuperAdminAuthedActivityRoute =
  SuperAdminAuthedActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => SuperAdminAuthedRoute,
  } as any)
const SuperAdminAuthedAdminsRoute = SuperAdminAuthedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperAdminAuthedRoute,
} as any)
const SuperAdminAuthedRestaurantsRoute =
  SuperAdminAuthedRestaurantsRouteImport.update({
    id: '/restaurants',
    path: '/restaurants',
    getParentRoute: () => SuperAdminAuthedRoute,
  } as any)
const SuperAdminAuthedSettingsRoute =
  SuperAdminAuthedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => SuperAdminAuthedRoute,
  } as any)
const AdminAuthedOrdersIndexRoute = AdminAuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedOrdersIdRoute = AdminAuthedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const SuperAdminAuthedRestaurantsIdRoute =
  SuperAdminAuthedRestaurantsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => SuperAdminAuthedRestaurantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/order/$token': typeof OrderTokenRoute
  '/super-admin': typeof SuperAdminAuthedRouteWithChildren
  '/admin/account': typeof AdminAuthedAccountRoute
  '/admin/analytics': typeof AdminAuthedAnalyticsRoute
  '/admin/delivery': typeof AdminAuthedDeliveryRoute
  '/admin/hours': typeof AdminAuthedHoursRoute
  '/admin/menu': typeof AdminAuthedMenuRoute
  '/admin/promotions': typeof AdminAuthedPromotionsRoute
  '/admin/staff': typeof AdminAuthedStaffRoute
  '/admin/reset-password/$token': typeof AdminResetPasswordTokenRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/super-admin/activity': typeof SuperAdminAuthedActivityRoute
  '/super-admin/admins': typeof SuperAdminAuthedAdminsRoute
  '/super-admin/restaurants': typeof SuperAdminAuthedRestaurantsRouteWithChildren
  '/super-admin/settings': typeof SuperAdminAuthedSettingsRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/super-admin/': typeof SuperAdminAuthedIndexRoute
  '/admin/orders/$id': typeof AdminAuthedOrdersIdRoute
  '/super-admin/restaurants/$id': typeof SuperAdminAuthedRestaurantsIdRoute
  '/admin/orders/': typeof AdminAuthedOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/order/$token': typeof OrderTokenRoute
  '/admin/account': typeof AdminAuthedAccountRoute
  '/admin/analytics': typeof AdminAuthedAnalyticsRoute
  '/admin/delivery': typeof AdminAuthedDeliveryRoute
  '/admin/hours': typeof AdminAuthedHoursRoute
  '/admin/menu': typeof AdminAuthedMenuRoute
  '/admin/promotions': typeof AdminAuthedPromotionsRoute
  '/admin/staff': typeof AdminAuthedStaffRoute
  '/admin/reset-password/$token': typeof AdminResetPasswordTokenRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/super-admin/activity': typeof SuperAdminAuthedActivityRoute
  '/super-admin/admins': typeof SuperAdminAuthedAdminsRoute
  '/super-admin/restaurants': typeof SuperAdminAuthedRestaurantsRouteWithChildren
  '/super-admin/settings': typeof SuperAdminAuthedSettingsRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/super-admin': typeof SuperAdminAuthedIndexRoute
  '/admin/orders/$id': typeof AdminAuthedOrdersIdRoute
  '/super-admin/restaurants/$id': typeof SuperAdminAuthedRestaurantsIdRoute
  '/admin/orders': typeof AdminAuthedOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/order/$token': typeof OrderTokenRoute
  '/super-admin/_authed': typeof SuperAdminAuthedRouteWithChildren
  '/admin/_authed/account': typeof AdminAuthedAccountRoute
  '/admin/_authed/analytics': typeof AdminAuthedAnalyticsRoute
  '/admin/_authed/delivery': typeof AdminAuthedDeliveryRoute
  '/admin/_authed/hours': typeof AdminAuthedHoursRoute
  '/admin/_authed/menu': typeof AdminAuthedMenuRoute
  '/admin/_authed/promotions': typeof AdminAuthedPromotionsRoute
  '/admin/_authed/staff': typeof AdminAuthedStaffRoute
  '/admin/reset-password/$token': typeof AdminResetPasswordTokenRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/super-admin/_authed/activity': typeof SuperAdminAuthedActivityRoute
  '/super-admin/_authed/admins': typeof SuperAdminAuthedAdminsRoute
  '/super-admin/_authed/restaurants': typeof SuperAdminAuthedRestaurantsRouteWithChildren
  '/super-admin/_authed/settings': typeof SuperAdminAuthedSettingsRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/super-admin/_authed/': typeof SuperAdminAuthedIndexRoute
  '/admin/_authed/orders/$id': typeof AdminAuthedOrdersIdRoute
  '/super-admin/_authed/restaurants/$id': typeof SuperAdminAuthedRestaurantsIdRoute
  '/admin/_authed/orders/': typeof AdminAuthedOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/order/$token'
    | '/super-admin'
    | '/admin/account'
    | '/admin/analytics'
    | '/admin/delivery'
    | '/admin/hours'
    | '/admin/menu'
    | '/admin/promotions'
    | '/admin/staff'
    | '/admin/reset-password/$token'
    | '/api/paystack/webhook'
    | '/super-admin/activity'
    | '/super-admin/admins'
    | '/super-admin/restaurants'
    | '/super-admin/settings'
    | '/admin/'
    | '/super-admin/'
    | '/admin/orders/$id'
    | '/super-admin/restaurants/$id'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/order/$token'
    | '/admin/account'
    | '/admin/analytics'
    | '/admin/delivery'
    | '/admin/hours'
    | '/admin/menu'
    | '/admin/promotions'
    | '/admin/staff'
    | '/admin/reset-password/$token'
    | '/api/paystack/webhook'
    | '/super-admin/activity'
    | '/super-admin/admins'
    | '/super-admin/restaurants'
    | '/super-admin/settings'
    | '/admin'
    | '/super-admin'
    | '/admin/orders/$id'
    | '/super-admin/restaurants/$id'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/admin/_authed'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/order/$token'
    | '/super-admin/_authed'
    | '/admin/_authed/account'
    | '/admin/_authed/analytics'
    | '/admin/_authed/delivery'
    | '/admin/_authed/hours'
    | '/admin/_authed/menu'
    | '/admin/_authed/promotions'
    | '/admin/_authed/staff'
    | '/admin/reset-password/$token'
    | '/api/paystack/webhook'
    | '/super-admin/_authed/activity'
    | '/super-admin/_authed/admins'
    | '/super-admin/_authed/restaurants'
    | '/super-admin/_authed/settings'
    | '/admin/_authed/'
    | '/super-admin/_authed/'
    | '/admin/_authed/orders/$id'
    | '/super-admin/_authed/restaurants/$id'
    | '/admin/_authed/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  OrderTokenRoute: typeof OrderTokenRoute
  SuperAdminAuthedRoute: typeof SuperAdminAuthedRouteWithChildren
  AdminResetPasswordTokenRoute: typeof AdminResetPasswordTokenRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$token': {
      id: '/order/$token'
      path: '/order/$token'
      fullPath: '/order/$token'
      preLoaderRoute: typeof OrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/_authed': {
      id: '/super-admin/_authed'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/account': {
      id: '/admin/_authed/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAuthedAccountRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/analytics': {
      id: '/admin/_authed/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAuthedAnalyticsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/delivery': {
      id: '/admin/_authed/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminAuthedDeliveryRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/hours': {
      id: '/admin/_authed/hours'
      path: '/hours'
      fullPath: '/admin/hours'
      preLoaderRoute: typeof AdminAuthedHoursRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/menu': {
      id: '/admin/_authed/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminAuthedMenuRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/promotions': {
      id: '/admin/_authed/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminAuthedPromotionsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/staff': {
      id: '/admin/_authed/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminAuthedStaffRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/reset-password/$token': {
      id: '/admin/reset-password/$token'
      path: '/admin/reset-password/$token'
      fullPath: '/admin/reset-password/$token'
      preLoaderRoute: typeof AdminResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/_authed/': {
      id: '/super-admin/_authed/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminAuthedIndexRouteImport
      parentRoute: typeof SuperAdminAuthedRoute
    }
    '/super-admin/_authed/activity': {
      id: '/super-admin/_authed/activity'
      path: '/activity'
      fullPath: '/super-admin/activity'
      preLoaderRoute: typeof SuperAdminAuthedActivityRouteImport
      parentRoute: typeof SuperAdminAuthedRoute
    }
    '/super-admin/_authed/admins': {
      id: '/super-admin/_authed/admins'
      path: '/admins'
      fullPath: '/super-admin/admins'
      preLoaderRoute: typeof SuperAdminAuthedAdminsRouteImport
      parentRoute: typeof SuperAdminAuthedRoute
    }
    '/super-admin/_authed/restaurants': {
      id: '/super-admin/_authed/restaurants'
      path: '/restaurants'
      fullPath: '/super-admin/restaurants'
      preLoaderRoute: typeof SuperAdminAuthedRestaurantsRouteImport
      parentRoute: typeof SuperAdminAuthedRoute
    }
    '/super-admin/_authed/settings': {
      id: '/super-admin/_authed/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminAuthedSettingsRouteImport
      parentRoute: typeof SuperAdminAuthedRoute
    }
    '/admin/_authed/orders/': {
      id: '/admin/_authed/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminAuthedOrdersIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/orders/$id': {
      id: '/admin/_authed/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminAuthedOrdersIdRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/super-admin/_authed/restaurants/$id': {
      id: '/super-admin/_authed/restaurants/$id'
      path: '/$id'
      fullPath: '/super-admin/restaurants/$id'
      preLoaderRoute: typeof SuperAdminAuthedRestaurantsIdRouteImport
      parentRoute: typeof SuperAdminAuthedRestaurantsRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedAccountRoute: typeof AdminAuthedAccountRoute
  AdminAuthedAnalyticsRoute: typeof AdminAuthedAnalyticsRoute
  AdminAuthedDeliveryRoute: typeof AdminAuthedDeliveryRoute
  AdminAuthedHoursRoute: typeof AdminAuthedHoursRoute
  AdminAuthedMenuRoute: typeof AdminAuthedMenuRoute
  AdminAuthedPromotionsRoute: typeof AdminAuthedPromotionsRoute
  AdminAuthedStaffRoute: typeof AdminAuthedStaffRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
  AdminAuthedOrdersIdRoute: typeof AdminAuthedOrdersIdRoute
  AdminAuthedOrdersIndexRoute: typeof AdminAuthedOrdersIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedAccountRoute: AdminAuthedAccountRoute,
  AdminAuthedAnalyticsRoute: AdminAuthedAnalyticsRoute,
  AdminAuthedDeliveryRoute: AdminAuthedDeliveryRoute,
  AdminAuthedHoursRoute: AdminAuthedHoursRoute,
  AdminAuthedMenuRoute: AdminAuthedMenuRoute,
  AdminAuthedPromotionsRoute: AdminAuthedPromotionsRoute,
  AdminAuthedStaffRoute: AdminAuthedStaffRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
  AdminAuthedOrdersIdRoute: AdminAuthedOrdersIdRoute,
  AdminAuthedOrdersIndexRoute: AdminAuthedOrdersIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

interface SuperAdminAuthedRestaurantsRouteChildren {
  SuperAdminAuthedRestaurantsIdRoute: typeof SuperAdminAuthedRestaurantsIdRoute
}

const SuperAdminAuthedRestaurantsRouteChildren: SuperAdminAuthedRestaurantsRouteChildren =
  {
    SuperAdminAuthedRestaurantsIdRoute: SuperAdminAuthedRestaurantsIdRoute,
  }

const SuperAdminAuthedRestaurantsRouteWithChildren =
  SuperAdminAuthedRestaurantsRoute._addFileChildren(
    SuperAdminAuthedRestaurantsRouteChildren,
  )

interface SuperAdminAuthedRouteChildren {
  SuperAdminAuthedActivityRoute: typeof SuperAdminAuthedActivityRoute
  SuperAdminAuthedAdminsRoute: typeof SuperAdminAuthedAdminsRoute
  SuperAdminAuthedRestaurantsRoute: typeof SuperAdminAuthedRestaurantsRouteWithChildren
  SuperAdminAuthedSettingsRoute: typeof SuperAdminAuthedSettingsRoute
  SuperAdminAuthedIndexRoute: typeof SuperAdminAuthedIndexRoute
}

const SuperAdminAuthedRouteChildren: SuperAdminAuthedRouteChildren = {
  SuperAdminAuthedActivityRoute: SuperAdminAuthedActivityRoute,
  SuperAdminAuthedAdminsRoute: SuperAdminAuthedAdminsRoute,
  SuperAdminAuthedRestaurantsRoute:
    SuperAdminAuthedRestaurantsRouteWithChildren,
  SuperAdminAuthedSettingsRoute: SuperAdminAuthedSettingsRoute,
  SuperAdminAuthedIndexRoute: SuperAdminAuthedIndexRoute,
}

const SuperAdminAuthedRouteWithChildren =
  SuperAdminAuthedRoute._addFileChildren(SuperAdminAuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  OrderTokenRoute: OrderTokenRoute,
  SuperAdminAuthedRoute: SuperAdminAuthedRouteWithChildren,
  AdminResetPasswordTokenRoute: AdminResetPasswordTokenRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
